version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Raise pull requests for version updates
    # against the `develop` branch
    target-branch: "develop"
    # Labels on pull requests for version updates
    labels:
      - "dependencies"
      - "security"
    # Specify version update preferences
    versioning-strategy: increase
    # Add reviewers
    reviewers:
      - "brokensound88"
    # Limit the number of open pull requests for version updates
    open-pull-requests-limit: 10
    # Allow up to 5 updates to be grouped together
    groups:
      dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    labels:
      - "ci-cd"
      - "dependencies"
    reviewers:
      - "brokensound88" 